/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequestCommand"];
                    "text/json": components["schemas"]["LoginRequestCommand"];
                    "application/*+json": components["schemas"]["LoginRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginRequestResponse"];
                        "application/json": components["schemas"]["LoginRequestResponse"];
                        "text/json": components["schemas"]["LoginRequestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequestModel"];
                    "text/json": components["schemas"]["RegisterRequestModel"];
                    "application/*+json": components["schemas"]["RegisterRequestModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisterResponseModel"];
                        "application/json": components["schemas"]["RegisterResponseModel"];
                        "text/json": components["schemas"]["RegisterResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form-schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FormSchemaCatalogResponse"];
                        "application/json": components["schemas"]["FormSchemaCatalogResponse"];
                        "text/json": components["schemas"]["FormSchemaCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form-schemas/{formType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    FormType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FormSchemaResponse"];
                        "application/json": components["schemas"]["FormSchemaResponse"];
                        "text/json": components["schemas"]["FormSchemaResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    FormType: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FormSchemaResponse"];
                    "text/json": components["schemas"]["FormSchemaResponse"];
                    "application/*+json": components["schemas"]["FormSchemaResponse"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FormSchemaResponse"];
                        "application/json": components["schemas"]["FormSchemaResponse"];
                        "text/json": components["schemas"]["FormSchemaResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        Payload?: string;
                        Files?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiveInspectionResponse"];
                        "application/json": components["schemas"]["ReceiveInspectionResponse"];
                        "text/json": components["schemas"]["ReceiveInspectionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetInspectionRequest"];
                    "text/json": components["schemas"]["GetInspectionRequest"];
                    "application/*+json": components["schemas"]["GetInspectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetInspectionResponse"];
                        "application/json": components["schemas"]["GetInspectionResponse"];
                        "text/json": components["schemas"]["GetInspectionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/{sessionId}/files/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                    fileName: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetInspectionFileRequest"];
                    "text/json": components["schemas"]["GetInspectionFileRequest"];
                    "application/*+json": components["schemas"]["GetInspectionFileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    TenantId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TenantBootstrapResponse"];
                        "application/json": components["schemas"]["TenantBootstrapResponse"];
                        "text/json": components["schemas"]["TenantBootstrapResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-config/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    TenantId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TenantBootstrapResponse"];
                    "text/json": components["schemas"]["TenantBootstrapResponse"];
                    "application/*+json": components["schemas"]["TenantBootstrapResponse"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TenantBootstrapResponse"];
                        "application/json": components["schemas"]["TenantBootstrapResponse"];
                        "text/json": components["schemas"]["TenantBootstrapResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translations/{language}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    language: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TranslationsResponse"];
                        "application/json": components["schemas"]["TranslationsResponse"];
                        "text/json": components["schemas"]["TranslationsResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    language: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TranslationsResponse"];
                    "text/json": components["schemas"]["TranslationsResponse"];
                    "application/*+json": components["schemas"]["TranslationsResponse"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TranslationsResponse"];
                        "application/json": components["schemas"]["TranslationsResponse"];
                        "text/json": components["schemas"]["TranslationsResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetUserRequest"];
                    "text/json": components["schemas"]["GetUserRequest"];
                    "application/*+json": components["schemas"]["GetUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserResponse"];
                        "application/json": components["schemas"]["GetUserResponse"];
                        "text/json": components["schemas"]["GetUserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MeResponse"];
                        "application/json": components["schemas"]["MeResponse"];
                        "text/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppTranslations: {
            title?: string | null;
            poweredBy?: string | null;
            brand?: string | null;
        } & {
            [key: string]: unknown;
        };
        CommonTranslations: {
            [key: string]: unknown;
        };
        ConditionalVisibilityResponse: {
            fieldId: string;
            value?: unknown;
            operator?: string | null;
        };
        ConnectivityTranslations: {
            [key: string]: unknown;
        };
        CustomizationTranslations: {
            [key: string]: unknown;
        };
        DebugInspectionTranslations: {
            [key: string]: unknown;
        };
        DrawersTranslations: {
            [key: string]: unknown;
        };
        FillFormTranslations: {
            [key: string]: unknown;
        };
        FormFieldOptionResponse: {
            label: string;
            value: string;
        };
        FormFieldResponse: {
            id: string;
            label: string;
            type: string;
            required?: boolean;
            externalID?: string | null;
            options?: components["schemas"]["FormFieldOptionResponse"][] | null;
            placeholder?: string | null;
            description?: string | null;
            validationRules?: components["schemas"]["ValidationRuleResponse"][] | null;
            visibleWhen?: components["schemas"]["ConditionalVisibilityResponse"][] | null;
            accept?: string | null;
            multiple?: boolean | null;
            capture?: string | null;
        };
        FormRendererTranslations: {
            [key: string]: unknown;
        };
        FormSchemaCatalogItemResponse: {
            formType?: string | null;
            version?: string | null;
            etag?: string | null;
        };
        FormSchemaCatalogResponse: {
            items?: components["schemas"]["FormSchemaCatalogItemResponse"][] | null;
        };
        FormSchemaResponse: {
            formName: string;
            sections: components["schemas"]["FormSectionResponse"][];
        };
        FormSectionResponse: {
            title: string;
            fields: components["schemas"]["FormFieldResponse"][];
        };
        FormTypesTranslations: {
            [key: string]: unknown;
        };
        GetInspectionFileRequest: {
            sessionId: string;
            fileName: string;
        };
        GetInspectionRequest: {
            sessionId: string;
        };
        GetInspectionResponse: {
            sessionId?: string | null;
            userId?: string | null;
            name?: string | null;
            queryParams?: {
                [key: string]: string;
            } | null;
            files?: components["schemas"]["InspectionFileReference"][] | null;
        };
        GetUserRequest: {
            userId: string;
        };
        GetUserResponse: {
            user?: components["schemas"]["UserModel"];
        };
        HomeTranslations: {
            [key: string]: unknown;
        };
        InspectionFileReference: {
            fileName?: string | null;
            sessionId?: string | null;
            fileType?: string | null;
        };
        InspectionStatsTranslations: {
            [key: string]: unknown;
        };
        LoginRequestCommand: {
            /** Format: email */
            email: string;
        };
        LoginRequestResponse: {
            userId?: string | null;
        };
        LoginTranslations: {
            [key: string]: unknown;
        };
        MeResponse: {
            userId?: string | null;
            roles?: string[] | null;
            permissions?: string[] | null;
        };
        MyInspectionsTranslations: {
            [key: string]: unknown;
        };
        NavTranslations: {
            [key: string]: unknown;
        };
        NewFormTranslations: {
            [key: string]: unknown;
        };
        NewInspectionTranslations: {
            [key: string]: unknown;
        };
        ReceiveInspectionResponse: {
            status?: string | null;
            sessionId?: string | null;
            name?: string | null;
            queryParams?: {
                [key: string]: string;
            } | null;
            message?: string | null;
        };
        RegisterRequestModel: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
        };
        RegisterResponseModel: {
            userId?: string | null;
        };
        RegisterTranslations: {
            [key: string]: unknown;
        };
        TenantBootstrapResponse: {
            tenantId: string;
            displayName: string;
            uiDefaults: components["schemas"]["UiDefaults"];
            enabledForms: string[];
            loginRequired?: boolean;
        };
        TranslationsResponse: {
            languageName: string;
            common?: components["schemas"]["CommonTranslations"];
            app: components["schemas"]["AppTranslations"];
            nav?: components["schemas"]["NavTranslations"];
            drawers?: components["schemas"]["DrawersTranslations"];
            connectivity?: components["schemas"]["ConnectivityTranslations"];
            inspectionStats?: components["schemas"]["InspectionStatsTranslations"];
            customization?: components["schemas"]["CustomizationTranslations"];
            uploadStatus?: components["schemas"]["UploadStatusTranslations"];
            formTypes?: components["schemas"]["FormTypesTranslations"];
            home?: components["schemas"]["HomeTranslations"];
            login?: components["schemas"]["LoginTranslations"];
            register?: components["schemas"]["RegisterTranslations"];
            newInspection?: components["schemas"]["NewInspectionTranslations"];
            newForm?: components["schemas"]["NewFormTranslations"];
            myInspections?: components["schemas"]["MyInspectionsTranslations"];
            fillForm?: components["schemas"]["FillFormTranslations"];
            debugInspection?: components["schemas"]["DebugInspectionTranslations"];
            formRenderer?: components["schemas"]["FormRendererTranslations"];
        };
        UiDefaults: {
            theme: string;
            font: string;
            language: string;
            showLeftFlyout?: boolean;
            showRightFlyout?: boolean;
            showInspectionStatsButton?: boolean;
        };
        UploadStatusTranslations: {
            [key: string]: unknown;
        };
        UserModel: {
            userId?: string | null;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
        };
        ValidationRuleResponse: {
            type: string;
            value?: unknown;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
